replicator:
  reader:
    connectionString: esdb://localhost:2114?tls=false
    protocol: grpc
  sink:
    connectionString: esdb://localhost:2114?tls=false
    protocol: grpc
    partitionCount: 1
    bufferSize: 1000
  scavenge: false
  filters: []
  checkpoint:
    path: "./replicator.chk"